name: Test CI for the AWS-SDK-TEST
on: 
    push:
        branches: 
            - master
            - 'release/*'

jobs: 
    build: 
        runs-on: windows-latest
        
        steps: 
            - name: Running the Build Job
              run: mvn package --file pom.xml
        
